<?php

/*
  Channel List
*/
$apis = array(
  'ustream' => array(
    "animustactics" => "Batman, Castlevania RoB &amp; SotN, Final Fantasy VII, requests",
    "asdfljg" => "Sonic 4 Episode 1", // Parax
    "assholeryman" => "Kingdom Hearts 2 and random stuff", // Axel Ryman
    "battalion-wars-2-speedrun" => "Batallion Wars 2",
    "bio-shock-2" => "Bioshock 2",
    "bluestarreturnssda" => "Mario 64, Zelda: OoT, and Diddy Kong Racing",
    "breakdown-gaming" => "Games that are awesome, except the ones that are not.",
    "cave-story-low-speedrun" => "Cave Story",
    "chrno" => "Rainbow Six, Various Gameboy Colour games",
    "craptacular-play" => "He's too cool for school. That's why he's at university.", // Hattori HANZo
    "deign" => "Donkey Kong Country",
    "dotjd" => "Super Metroid, Rocket Knight Adventures",
    "dragonfang" => "Chibi Robo",
    "droogie-like-whoa" => "Super Mario 1 and 3, Super Mario World 2, Metal Gear Solid 2",
    "Electrochock" => "Random Stuff",
    "emptyeye's-speedrun-practice" => "Air Fortress, Phantasy Star II casual play",
    "essentia-s-speedruns" => "Final Fantasy 6, Donkey Kong Country 2",
    "exes-stream" => "Super Mario 64, Biohazard 2, Zelda: Ocarina of Time, other gaming",
    "ffgamer86" => "Spanky's Quest, LTTP, Other",
    "fisherrob-channel" => "Stuff",
    "flip714" => "Wario Land: Shake It!, other stuff",
    "i-like-glasses" => "Zelda: A Link to the Past", // Kryssstal
    "icheatatgolf" => "Super Metroid",
    "idkbutlike2" => "Playing whatever I want, whenever I want, and however I want!",
    "imamyth-colosseum-presents" => "Dracula X Rondo of Blood, Rhapsody",
    "justingroton-gamez" => "Kirby's Epic Yarn, Donkey Kong Jungle Beat",
    "kareshi-tv" => "Super Ghouls 'n Ghosts high score, Ghosts 'n Goblins, Jaws",
    "kbladeruns" => "Stuff",
    "krz" => "Stuff",
    "let-s-play-mass-effect" => "Mass Effect 2",
    "manjackal" => "Jackal",
    "mega-man-2-ta" => "Megaman series",
    "milessmb" => "Metroid Prime 1/2",
    "nhouzxm" => "Generic gaming",
    "nitrodon" => "Cave Story",
    "opario" => "Ico, Shadow of the Colossus, Kingdom Hearts, KH: Chain of Memories, KHII",
    "riskbreakery" => "Double Dragon 3",
    "s-for-serious" => "Serious Sam",
    "speed-running" => "Gears of War",
    "sprintgod" => "Braid, Streets of Rage 2",
    "strangenessdss" => "Blast Corps, Wario World, other stuff",
    "the-khan-zone" => "Air Fortress, Double Dragon",
    "the-swedish-cow" => "Genesis games and Serious Sam",
    "TheNewJStream" => "La-Mulana, lots of random gaming",
    "toufool31" => "Super Mario Galaxy 2",
    "trekhaak" => "Trekhaak's stream",
    "ucpro-s-speedrun-attemtps" => "Super Mario Bros. Wii",
    "vorpaledge" => "Rocket Knight Adventures, Super Metroid",
    "worxx" => "ALTTP, Mario Kart, Mario RPG, Off-Road, Donkey Kong Country, Castlevania, Super Metroid",
  ),
  "justin" => array(
    "andrewg1990" => "Mario (duh), classic arcade games",
    "animeowzerz" => "Mystical Ninja 64, Donkey Kong 64, Zelda OoT",
    "arrowspace" => " ",
    "calebhart42" => "Megaman X",
    "carcinogensda" => "Resident Evil",
    "carlsagan42" => "Yoshi's Island",
    "cheaterhater" => "Tony Hawk's Pro Skater 4",
    "chumlum" => "Rocket Knight Adventures, Touhou",
    "cosmowright" => "Super Monkey Ball, Ocarina of Time",
    "cyghfer" => "Currently: Super Mario RPG & Trip World",
    "darkeye14" => "Metroid Prime, Rocket Knight Adventures, Contra: Hard Corps, Super Metroid, SM64",
    "dee_ehn" => "Zelda (Link to the Past primarily), Megaman, Castlevania, Mario, RPGs, racing",
    "dessyreqt" => "Super Metroid, Mega Man X, SotN, and SM64",
    "duckfist" => "Megaman 10",
    "dunnius" => "NES Metal Gear, ActRaiser 1, TASing",
    "elminster45" => "Ocarina of Time, Majora's Mask",
    "exosda" => "SNES, GB, N64, PSX and PS2",
    "feasel" => "Snake Rattle N Roll, Rescue Rangers, Limbo, etc",
    "flickyish" => "Bayonetta",
    "heidrage" => "Summoner: A Goddess Reborn, Super C, other stuff",
    "honorablejay" => "Arkham Asylum, Jedi Academy, Vampire: Bloodlines",
    "ilseroth" => "Fable 2",
    "ingx24" => "Majora's Mask, Ocarina of Time, Super Mario 64",
    "joe69420" => "Super Meat Boy, Super Mario 64",
    "kingnahum18" => "X-Men, Metroid Fusion",
    "kiyura" => "Enter the Matrix",
    "klaige" => "Rescue Rangers, Final Fight 3",
    "lambdan" => "GTA, SM64, Zelda, Xbox, Wii and random games",
    "manbearpig7" => "Link to the Past, Megaman 10, Super Mario 64, Super Mario Bros. 3", // Mr. Piggy
    "mecha_richter" => "Hard Corps Uprising, Jumping Flash 2",
    "mikwuyma" => "Sunset Riders, random games",
    "moizt" => "Pokemon Red, Super Mario 64, 3D Zelda, other casual gaming",
    "murderbydeath" => "A Link To The Past",
    "obdajr" => "Megaman 7, Misadventures of Tron Bonne, Legend of Dragoon, Link to the Past",
    "peaches__" => "Blast Corps",
    "pjdicesare" => "Battletoads, Actraiser, Lagoon, 7th Saga, other misc bad games",
    "playe" => "Ocarina of Time, Metroid Prime 1/2, Majora's Mask",
    "pokeyil" => "Ocarina of Time",
    "puwexil" => "Kingdom Hearts II, other action RPGs",
    "raijinnoxblade" => "Megaman X series, other stuff",
    "raneofsotn" => "SOTN, Seiken Densetsu 3, Brain Lord, Ninja Warriors",
    "reaif" => "Zelda, Super Metroid and others",
    "red_kryal" => "Mega Man Xtreme 2, other random stuff",
    "ringrush" => "Donkey Kong 64, Sonic and the Secret Rings, Banjo Kazooie",
    "rolanmen1" => "Megaman X and Zero Series, Sometimes TASing",
    "romscout" => "Mario RPG, SOTN, Kirby's Dream Land",
    "runnerguy2489" => "3D Zelda series",
    "shaddod2" => "Legend of Zelda series, Final Fantasy Crystal Chronicles",
    "sicko2012" => "THE GREAT SICKO http://www.youtube.com/watch?v=UBbhTdCf6SM#t=57s",
    "slipomatic" => "Random gaming",
    "sonikkustar" => "Metal Slug",
    "sportacus84" => "Random gaming",
    "srkfunkdoc" => "Castlevania 1/3/4, FF Mystic Quest, Maximum Carnage, lots of obscure stuff",
    "sunjiano" => "Super Mario 64, Super Monkey Ball",
    "surreal_" => "Megaman X1/2, Twilight Princess",
    "theonly0" => "Super Mario Galaxy",
    "tiki77747" => "Mega Man classic & X series",
    "tranquilite" => "VVVVVV, casual stuff",
    "trihex" => "Super Mario World 2: Yoshi's Island",
    "tropicallo_" => "Donkey Kong (GB)",
    "wingedzyre" => "Skies of Arcadia Legends",
    "witwix" => "Super Mario 64, Link to the Past",
    "yoshiiscool" => "Megaman series",
    "zaibirquild" => " ",
    "zenicreverie" => "Vandal Hearts, other stuff",
    "eisenefaust" => "FF2 and random games",
    "aleckermit" => "007: Agent Under Fire",
    "masterwill" => "Final Fantasy VI and Zelda: A Link to the Past",
    "khaos4wood" => "Resident Evil series, PC FPS games, other random stuff",
    "yggdrizzle" => "Mega Man Classic & X, other NES/SNES games", // rockmanchan
    "rggibson" => "Mega Man classics, random Genesis games",
    "hurblat" => "Contra 3",
    "lidholt" => "World of Illusion", // Edenal
    "metasigma" => "Mega Man X, Red Star, RPGs",
    "aphox" => "The Witcher 2", // Lordy
    "lxx4xnx6xxl" => "Super Metroid",
    "hacksaw11" => "Lufia 2, SNES games",
    "unpronounceable" => "Dr. Mario, Cave Story", // mocliamtoh
    "uraniumanchor" => "Blaster Master, random stuff",
    "axon64" => "Mega Man X",
    "mister___k" => "Contra 3",
    "tjp7154" => "Donkey Kong Country, Dark Cloud 2",
    "mike89sda" => "Sonic 3, other funky stuff",
    "venick409" => "Megaman Zero",
    "lagdotcom" => "Klonoa 2",
    "shadowjacky" => "Rocket Knight Adventures, Aero The Acrobat, Misc",
    "speeddemosarchivesda" => "Believe it.",
    "0xwas" => "Stuff",
    "quirkee" => "OoT, Trauma Center Second Opinion, others",
    "stevethedreamer" => "He's Steve. He's a dreamer.",
    "brsmstr" => "Wii, Xbox 360",
    "link98" => "Zelda: Ocarina of Time",
    "ktwo" => "NES",
    "cody_miller" => "Super Meat Boy",
    "indextic" => "The Darkness",
    "crypticjacknife" => "DKC series (including DKCR), Turok: Evolution",
    "darkwing_duck_sda" => "Older Nintendo games",
    "alexandrebritos" => array("add" => array("synopsis" => "Mirror's Edge", "screenname" => "Brossentia")),
  ),
  "twitch" => array(
    "gogobmn" => "Metal Gear Solid 2, Trauma Center/Team, Uplink, casuals",
    "aftermathrar" => "Castlevania series, Darksiders",
    "crystalseafate" => "Mega Man 9",
  ),
);

$include = array('user_name', 'channel_name', 'channel_url', 'embed_stream', 'online', 'api');
$callback = 'sda_stream';
$ttl = 0.5;

$post = function(&$s) {
  $s->set_embed_dimensions(320, 260);
};

SDAExceptions::set_error_level(E_USER_NOTICE);
