<?php

/*
  Channel List
*/
$apis = array(
  'ustream' => array(
    //10/12 "animustactics" => "Batman, Castlevania RoB &amp; SotN, Final Fantasy VII, requests",
    "bio-shock-2" => "Bioshock 2",
    "cave-story-low-speedrun" => "Cave Story",
    //10/10 "deign" => "Donkey Kong Country",
    //11/03 "dotjd" => "Super Metroid, Rocket Knight Adventures",
    //10/08 "dragonfang" => "Chibi Robo",
    //11/04 "exes-stream" => "Super Mario 64, Biohazard 2, Zelda: Ocarina of Time, other gaming",
    "icheatatgolf" => "Super Metroid",
    //10/11 "idkbutlike2" => "Playing whatever I want, whenever I want, and however I want!",
    //11/04 "justingroton-gamez" => "Kirby's Epic Yarn, Donkey Kong Jungle Beat",
    //11/04 "kbladeruns" => "Stuff",
    //10/6 mega-man-2-ta" => "Megaman series",
    "nhouzxm" => "Generic gaming",
    "opario" => "Ico, Shadow of the Colossus, Kingdom Hearts, KH: Chain of Memories, KHII",
    //10/08 "riskbreakery" => "Double Dragon 3",
    //10/11 "sprintgod" => "Braid, Streets of Rage 2",
    //10/07 "strangenessdss" => "Blast Corps, Wario World, other stuff",
    //11/01 "the-khan-zone" => "Air Fortress, Double Dragon",
    "toufool31" => "Super Mario Galaxy 2",
    //10/05 "ucpro-s-speedrun-attemtps" => "Super Mario Bros. Wii",
    //11/04 "worxx" => "ALTTP, Mario Kart, Mario RPG, Off-Road, Donkey Kong Country, Castlevania, Super Metroid",
    "insert-title1" => array("add" => array("synopsis" => "PlayStation Platformers and/or challenge runs", "screenname" => "I have no name")),
    "trr03" => "Metroid Prime",
    "speedrun-testing" => "Alisia Dragoon", // toothache
  ),
  "twitch" => array(
    "0xwas" => "Stuff",
    "aleckermit" => "007: Agent Under Fire",
    "andrewg1990" => "Mario (duh), classic arcade games",
    "animeowzerz" => "Mystical Ninja 64, Donkey Kong 64, Zelda OoT",
    "aphox" => "The Witcher 2", // Lordy
    "arrowspace" => array("add" => array("synopsis" => "Katamari and other weird games", "screenname" => "Arrow")),
    "axelryman" => "Kingdom Hearts 2 and random stuff",
    "axon64" => "Mega Man X",
    "brsmstr" => array("add" => array("synopsis" => "Wii, Xbox 360", "screenname" => "Brassmaster")),
    "calebhart42" => "Megaman X",
    "call_me_greedo" => "Aria of Sorrow, Zero Mission, other Castleroids, Zelda",
    "carcinogensda" => "Resident Evil",
    "carlsagan42" => "Yoshi's Island",
    "cheaterhater" => "Tony Hawk's Pro Skater 4",
    "chumlum" => "Rocket Knight Adventures, Touhou",
    "cody_miller" => "Super Meat Boy",
    "cosmowright" => "Super Monkey Ball, Ocarina of Time",
    "cpkaka" => "Super Mario 64, Super Street Fighter 4",
    "crypticjacknife" => "DKC series (including DKCR), Turok: Evolution",
    "cyghfer" => "Currently: Super Mario RPG & Trip World",
    "darkeye14" => "F-Zero GX",
    "darkwing_duck_sda" => array("add" => array("synopsis" => "Older Nintendo games", "screenname" => "Darkwing Duck")),
    "dee_ehn" => "Zelda (Link to the Past primarily), Megaman, Castlevania, Mario, RPGs, racing",
    "dessyreqt" => "Super Metroid, Mega Man X, SotN, and SM64",
    "duckfist" => "Megaman 10",
    "dunnius" => "NES and MSX Metal Gear, ActRaiser 1, TASing",
    "eisenefaust" => "FF2 and random games",
    "elminster45" => "Ocarina of Time, The Wind Waker",
    "feasel" => "Speedrun attempts and racing on NES/SNES/etc",
    "flickyish" => "Bayonetta",
    "fragmaster01" => "Iji",
    "hacksaw11" => "Lufia 2, SNES games",
    "heidrage" => "Summoner: A Goddess Reborn, Super C, other stuff",
    "honorablejay" => "Arkham Asylum, Jedi Academy, Vampire: Bloodlines",
    "hurblat" => "Contra 3",
    "ilseroth" => "Fable 2, Skyrim",
    "indextic" => "The Darkness",
    "ingx24" => "Majora's Mask, Ocarina of Time, Super Mario 64",
    "joe69420" => "Super Meat Boy, Super Mario 64",
    "khaos4wood" => "Resident Evil series, PC FPS games, other random stuff",
    "kibb0" => "Serious Sam",
    "kingnahum17" => "Metroid Fusion, Dark Souls, Tomb Raider, Bioshock series",
    "klaige" => "Rescue Rangers, Final Fight 3",
    // "ktwo123" => "NES",
    "lagdotcom" => "Klonoa 2",
    "lambdan" => array("add" => array("synopsis" => "Super Mario 64, Zelda OoT, and random", "screenname" => "DJS")),
    "link98" => "Zelda: Ocarina of Time",
    // "lxx4xnx6xxl" => "Super Metroid",
    "manbearpig7" => "Link to the Past, Megaman 10, Super Mario 64, Super Mario Bros. 3", // Mr. Piggy
    "masterwill" => "Final Fantasy VI and Zelda: A Link to the Past",
    "mecharichter" => "Castlevania SOTN Richter, poverty games",
    "megaultrajman" => "La-Mulana, lots of random gaming",
    "metasigma" => "Mega Man X, Red Star, RPGs",
    "mike89sda" => "Sonic 3, other funky stuff",
    "mikwuyma" => "Sunset Riders, random games",
    "mister___k" => "Contra 3",
    "moizt" => "Wario Land 2, Pok&eacute;mon Blue",
    "murderbydeath" => "A Link To The Past",
    "naegleria" => "Sonic 1, Shadow of the Colossus, random stuff",
    "obdajr" => "Megaman 7, Misadventures of Tron Bonne, Legend of Dragoon, Link to the Past",
    "oozaroo1" => "Symphony of the Night, random games",
    "peaches__" => "Blast Corps",
    "pheenoh" => "3D Zelda Series",
    "pjdicesare" => "Battletoads, Actraiser, Lagoon, 7th Saga, other misc bad games",
    "playe" => "Ocarina of Time, Metroid Prime 1/2, Majora's Mask",
    "pokeyil" => "Ocarina of Time",
    "puwexil" => "Kingdom Hearts series, Final Fantasy series, other Action RPGs/JRPGs",
    "quirkee" => "OoT, Trauma Center Second Opinion, others",
    "raelcun" => "Starcraft 2, random RPGs",
    "raijinnoxblade" => "Megaman X series, other stuff",
    "raneofsotn" => "SOTN, Seiken Densetsu 3, Brain Lord, Ninja Warriors",
    "reaif" => "Zelda, Super Metroid and others",
    "red_kryal" => "Mega Man Xtreme 2, other random stuff",
    "rggibson" => "Mega Man classics, random Genesis games",
    "ringrush" => "Donkey Kong 64, Sonic and the Secret Rings, Banjo Kazooie",
    "rolanmen1" => "Megaman X and Zero Series, Sometimes TASing",
    "romscout" => "Mario RPG, SOTN, Kirby's Dream Land",
    "runnerguy2489" => "3D Zelda series",
    "shaddod2" => "Legend of Zelda series, Final Fantasy Crystal Chronicles",
    "shadowjacky" => "Rocket Knight Adventures, Aero The Acrobat, Misc",
    "sicko2012" => "THE GREAT SICKO http://www.youtube.com/watch?v=UBbhTdCf6SM#t=57s",
    "siglemic" => "Super Mario 64",
    "slipomatic" => "Random gaming",
    "sonikkustar" => "Metal Slug, Sonic, Random Games",
    "speeddemosarchivesda" => "Believe it.",
    "sportacus84" => "Random gaming",
    "srkfunkdoc" => "Castlevania 1/3/4, FF Mystic Quest, Maximum Carnage, lots of obscure stuff",
    "stevethedreamer" => "He's Steve. He's a dreamer.",
    "sunjiano" => "Super Mario 64, Super Monkey Ball",
    "surreal_" => "Megaman X, Spyro, Sly Cooper, Ape Escape 3",
    "teekayy" => "Seiken Densetsu",
    "theonly0" => "Super Mario Galaxy",
    "the_hattori_hanzo" => "He's too cool for school. That's why he's at university.",
    "tiki77747" => "Mega Man classic & X series",
    "tjp7154" => "Donkey Kong Country, Dark Cloud 2",
    //"toothache42" => "Alisia Dragoon", moved to ustream
    "tranquilite" => "VVVVVV, casual stuff",
    "trihex" => "Super Mario World 2: Yoshi's Island",
    "tropicallo_" => "Donkey Kong (GB)",
    "uraniumanchor" => "Blaster Master, random stuff",
    "venick409" => "Megaman Zero",
    "welpenhund" => "A Link to the Past, Legend of Zelda, Mario Kart, Portal 2",
    "wingedzyre" => array("add" => array("synopsis" => "Decap Attack, Sonic 3D Blast, random games", "screenname" => "Zyre")),
    "yggdrizzle" => "Mega Man Classic & X, other NES/SNES games", // rockmanchan
    "yoshiiscool" => "Megaman series",
    "zaibirquild" => " ",
    "zenicreverie" => "RPGs, Speedruns, and Backloggery Shenanigans",
    "rocmox" => "Majora's Mask",
    "dram55" => "Super Mario World, Yoshi's Island, Super Nintendo",
    //"jazzmastergold" => "Streaming for fun with a side of speedrunning MW2 and Kirby: NiDL",
    "darkkobold" => "Turbografx-16",
    "adam_ak" => "Sonic Chaos, Monster Hunter 3",
    "aftermathrar" => "Castlevania series, Darksiders",
    "breakdown777" => "An eclectic selection",
    "caracarnvi" => "Final Fantasy X, maybe other random games",
    "crystalseafate" => "Mega Man 9",
    "demitrius7" => "Final Fantasy IX, King of Dragons",
    "droogie1xp" => "Super Mario 1 and 3, Super Mario World 2, Metal Gear Solid 2",
    "essentiafour" => "Chrono Trigger and other RPGs",
    "exosda" => array("add" => array("synopsis" => "Everything", "screenname" => "Exo")),
    "fisherrob86" => "Stuff", // Mickey_Mage
    "gogobmn" => array("add" => array("synopsis" => "Metal Gear Solid 2, Trauma Center/Team, Uplink, casuals", "screenname" => "bmn")),
    "ikomasoji" => "Mega Man X series, Brave Fencer Musashi, Blood Omen, other random games",
    "kariohki" => "Silhouette Mirage and random non-speedrun games",
    //"mapler90210" => "Aria of Sorrow, Portal, and the occastional whims",
    "nitrodon" => "Cave Story",
    "oasiz____" => array("add" => array("synopsis" => "GTA3 and random gaming", "screenname" => "oasiz")),
    "ozzy__88" => array("add" => array("synopsis" => "SotN and Super Castlevania IV", "screenname" => "ozzy88")),
    "paladrima" => "Ocarina of Time, Oracle of Seasons",
    // "raen_" => "Wind Waker, The Legend of Zelda, and other great games",
    "skiazyk" => "Psychonauts",
    "youkaidragoon" => "Gears of War",
    "zallard1" => "Punch Out Wii, Splatterhouse, and Star Fox 64 highscores?",
    "dragondarchsda" => "Mostly RPGs, and some other randomages",
    "kinghippo423" => "Link To The Past, Legend of Zelda, Super Mario World, Super Mario 64, Where's Waldo",
    "trekhaakterror" => "Trekhaak's stream",
    "evussen" => "Steam games &amp; JRPGs",
    "greenalinksda" => "Direct Feed DS games, Nintendo/SEGA Consoles and XBLA",
    "uchihasda" => "F-Zero, Mario Kart, Metroid, Zelda series and other games",
    "zachsk" => "Flash gaming",
    "sir_vg" => "RPGs are the Spice of Life",
    "yoshifan28" => "Mario, Sonic, and others",
    "lee_sda" => "Yoshi's Island practice, and other failtastic endeavors",
    "svenne1138" => "Zelda II &amp; Super Mario Bros. 2",
    "cfox7" => "Super Mario 64, Ocarina of Time",
    "lee_sda" => "Yoshi's Island practice, and other failtastic endeavors",
    "c_moooh" => "Genesis games and Serious Sam",
    "tompa" => "Zelda and SNES",
    "z1mb0bw4y" => "Alice: Madness Returns, Super Meat Boy",
    "emptyeye" => "That Guy in the Cape",
    "kruzz" => "Stuff",
    "theenglishman" => "Resident Evil 4, Batman: Arkham City",
    "theseawolf1" => "Castlevania 2: Simon's Quest",
    "IrregularJinny" => "Rockman X/X3, Mega Man 10, Klonoa",
    "edenalsda" => "World of Illusion, Tiny Toon Adventures: Buster Busts Loose!",
    "murphagator" => "Very bad things",
    "xelotath" => array("add" => array("synopsis" => "Rollergames and other games", "screenname" => "Xelotath")),
    "shiden86" => array("add" => array("synopsis" => "Ys &amp; Mega Man 6 plus other stuff", "screenname" => "Shiden")),
    "chrnothesinner" => "Skyrim speedrunning and other bowl clippory!",
    "andreluclevesque" => array("add" => array("synopsis" => "Amnesia, Super Meat Boy, Paper Mario, Tales of Symphonia, Mario Sunshine and Lost Kingdoms 2", "screenname" => "Andr&eacute;LucL&eacute;vesque")),
    "ChristosOwen" => "A Link to the Past &amp; Super Mario World",
    "lemonsx" => array("add" => array("synopsis" => "Terranigma and other RPGs", "screenname" => "Lemon")),
    "thesundaysequencebreak" => array("add" => array("synopsis" => "Live speedrunning chat", "screenname" => "The Sunday Sequence Break")),
    "pirate109" => "Super Meat Boy speedrunning, other random games occasionally",
    "agedude44" => "Batallion Wars 2",
    "poxnor" => "Final Fantasy 8, The Final Fantasy Legend",
    "krimmydoodle" => "MegaMari, RosenkreuzStilette, Super Metroid",
    "kirkq" => "Bomberman, Blast Corps",
    "Purity_the_Kitty" => "Zelda, Megaman, CV, and Whatever",
    "drsynj" => "Crash Twinsanity, Spyro 2&colon; Gateway to Glimmer and Final Fantasy XIII-2",
    // "rendood" => "Mega Man, Contra, old-school stuff",
    "electrochock13" => "Random Stuff",
    "omnigamer" => array("add" => array("synopsis" => "Skyblazer, Nier, random uncommon games", "screenname" => "Omnigamer")),
    "korzic" => "Ys I & II Complete, Ys Origin",
    // "hsanrb" => "Mean Bean, Columns, mostly other Sega titles", requested
    "arkhanno" => "I Wanna Be The Guy",
    "sinisterwon" => "Ninja Gaiden, Mike Tyson's Punch Out!!, NES, SNES",
    "ffgamer86" => "Spanky's Quest, LTTP, Other",
    "babloization" => "Super Castlevania IV, random races",
    "parax0" => "Sonic 4 Episode 1",
    "spikevegeta" => "Rayman Origins, KH2, All Requests",
    "egonomics651" => "ARES: Extinction Agenda, Hook (SNES) and FF Mystic Quest",
    "chuckledow" => "Mass Effect 3, Random XBLA/PSN Games",
    "mgslade" => "Metal Gear Solid",
    "lthanatosl" => "Dark Souls, Demon's Souls",
    "nidokingftw" => "Resident Evil 4",
    "the_kareshi" => "Classic gaming, videogame piano",
    "ilikeyourbootybutlmnotgay" => "Journey to Silius",
    "mexiricanbassmonkey" => "Pkmn Crystal, Pkmn Leaf Green, Random RPGs",
    "trdef" => "Actraiser, Kirby's Dreamland",
    "VorpalSDA" => "Rocket Knight Adventures, Super Metroid",
    "kryssstal" => "Zelda: A Link to the Past",
    "theterribleone" => array("add" => array("synopsis" => "Zelda: A Link to the Past", "screenname" => "T1")),
    "trushade" => array("add" => array("synopsis" => "Resident Evil: ORC, DWM2", "screenname" => "TrUShade")),
    "ibldedibble" => "PC games, probably mostly indiegames",
    "garrison_tt" => array("add" => array("synopsis" => "Super Metroid", "screenname" => "Garrison")),
    "khananaphone" => array("add" => array("synopsis" => "Cobra Triangle", "screenname" => "KHANanaphone")),
    "sirfist" => array("add" => array("synopsis" => "Dark Souls, DKC2, Most consoles", "screenname" => "Sir Fist")),
    "sda_tamik" => "Bastion",
    "hiddenpower13" => "Super Mario Sunshine",
    "fieryblizzard" => "VVVVVV",
    "toesmybros" => "Donkey Kong 64, Paper Mario, Banjo-Tooie",
    "ludendi" => "NES and SNES Speedrunning",
    "caneofpacci" => "Crash Bandicoot",
    "testrunner" => "Skyward Sword, Super Metroid",
    "aneeslol" => "Super Mario Sunshine, Glover",
    "anwonu" => "GBA/DS games",
    "smilge" => "Baldur's Gate 2",
    "karls_friend" => "Ape Escape, 3D Simian Games",
    "zastbat" => "Legacy of Kain and Omega Boost",
    "makar4eva" => "Future Tactics: The Uprising",
    "potatohandle" => "Lost Odyssey speedrun planning. (And other stuff)",
    "thekotti" => "Hitman, Penumbra, PC games",
    "YayMarsha" => "Metal Gear Solid 3 and God Hand", // Molotov
    "takujiz" => "Super Meat Boy, Portal series, Quake, DotA2",
    "threecow" => "Devil May Cry 3 Special Edition",
    "osey889" => "Dead Space 2",
    "TheVost" => "Toy Story 2: Buzz Lightyear to the Rescue",
    "thethrillness" => "Metal Gear Solid, Resident Evil",
    "TomSinister" => "Super Street Fighter 4 Trials Mode",
    "mrspeedrun" => "Metroid Prime, Metroid Prime 2 Echoes",
    "jmc4789" => "MegaMan Legends series",
    "crystalbeauty" => "Final Fantasy, and Tales Of series",
    "kirbymastah" => "Metroid Fusion, Metroid Prime 2, Kirby's Return to Dreamland",
    "bangerra" => "Kirby's Dream Land, DuckTales, The Lion King",
    "ridd3r" => "Max Payne",
    "exisidis2" => "Metal Gear Solid, Resident Evil, Zelda, NES retro gaming",
    "iastsa" => "Dungeon Magic, Random Games",
    "ohbeejay" => "Bastion, Black Mesa",
    "usedpizza" => "Mega Man 10, Paper Mario",
    "vugmer" => "Jackal",
    "milessmb" => "Metroid Prime 1/2",
    "northern_one" => array("add" => array("synopsis" => "Blood", "screenname" => "Northern")),
    "Anemptybox" => "Timesplitters series",
    "kakka_rot" => "Fatal Frame, Metal Gear Solid 2",
    "xarthok" => "Commander Keen series",
    "minasdurion" => "Mega Man 3, Trapt (PS 2), Luigis Mansion",
    "eckoap91" => "DKC Returns, NSMB Wii, Kirby Adventure Wii, SMG2, Bomberman 64",
    "presjpolk" => "Zelda, Zelda 2, Ultima, Mega Man, Faxanadu",
    "chokehold_" => "Okami HD",
    "yagamoth" => "I Wanna Be The Guy: Gaiden",
    "boxfat" => "NES platformers and isometric wizard games",
    "brossentia" => "Mirror's Edge",
    "zewing" => "Yoshi's Island, Mega Man X3, Ys 3, Lufia, Secret of the Stars",
    "garik16" => "Legend of Legaia",
    "deliciouspi" => "La-Mulana",
    "jkoper" => "Zelda, Mario, and Other Stuff",
    "omegagalax" => "Wario World, Zelda, Mario",
    "kiyura" => "Enter the Matrix",
    "invis_" => "Mirror's Edge, Skyrim",
    "rudyxx" => "Haunting Ground, Rhapsody A Musical Adventure, and Spy Fiction",
    "silverboxer" => "Probably Super Monkey Ball",
    "kubelwagon185" => "Old DOS games",
    "sambrea" => "Gamer and Stitcher",
    "joshkaz" => "Onimusha, Simpsons Arcade, The Bouncer, and other stuff",
    "drakonsan" => "Shadowrun", // hasn't streamed?
    "buttersbb" => "Lifeline, Zool, Rune Factory 3, Poverty",
    "fiercekyo" => "Resident Evil 2",
    "cvagts" => "Suikoden series, various RPGs",
    "reed_tiburon" => "Bangai-O HD: Missile Fury",
    "hokorippoi" => "Mass Effect 2",
    "atlasnr" => "Metroid Prime",
    "lotsofs" => "Half-Life 2, Grand Theft Auto: Vice City/San Andreas, various other PC games",
    "decidedsloth" => "Dishonored and other PC games",
    "zombietraine" => "Castlevania 2: Simon's Quest and other 8-bit/16-bit RPGs",
    "epicerror" => "Bioshock Infinite",
    "ryuken1315" => "Azure Dreams",
    "wmjspeedruns" => "F-Zero X, Wipeout series, Shadow Man and other retro games",
    "kanban85" => "Braid",
    "vulajin" => "Pok&eacute;mon Black, Pok&eacute;mon White 2, Bastion, Dust: An Elysian Tail",
    "exe_de" => array("add" => array("screenname" => "exe", "synopsis" => "Gex: Enter the Gecko")),
    "valiuse" => "Final Fantasy, PC games, Other games",
    "pro_jn" => "Zelda 2",
    "the2012robot" => "The Legend of Dragoon, Resident Evil 4, Star Ocean 2",
    "eumoria_ttv" => "Gyruss",
    "ghost_wheel" => "KH: Chain of Memories, KH2, 3rd gen Pokemon, Mega Man 9, and other RPGs",
    "neohart" => "Final Fantasy series",
    "nlg_organisation" => "Super Mario Kart, GoldenEye007, Donkey Kong Country Returns",
    "rinimt" => "Final Fantasy, Star Ocean",
    "radixsda" => "Final Fantasy 11",
    "MrBean35000vr" => "Crash Bandicoot 2, Mario Kart Wii, Oddworld: Abe's Oddysee",
    "livinglooneybin" => "Dead Space 2 &amp; 3",
    "wypy" => "Final Fantasy 6, 7 &amp; 10, The Walking Dead (Telltale)",
    "saintconnor" => "Blasto, Contra and Super C, and drinking beer while doing so",
    "lurkchan" => "Vampire: The Masquerade - Bloodlines, Batman the video game",
    "CaneCraft" => "Sacrifice, Commander Keen Series, DOS Games, Platformers",
    "biosp4rk" => "Metroid Fusion",
    "sunblade89" => "Resident Evil 4, Metroid Prime",
    "mitchflowerpower" => "Mario 3, Mega Man 10, Metroid",
    "ccaakk" => "Super Mario Bros. 2, Metroid, Pitfall II",
    "spocky77" => "MDK",
    "ls400hurdles" => "Brave Fencer Musashi",
    "mman235" => "Tomb Raider",
    "smk_machine" => "Super Mario Kart",
    "darbian" => "Super Mario Bros., Cool Spot, World of Illusion",
    "kingdomnerdia" => "Mark of the Ninja, Dota 2",
    "inzult2" => "Zelda 2, various bad NES games",
    "dttcyrax" => "PC and old school games - speedruns for days",
    "vykan12" => "Fire Emblem Radiant Dawn",
    "leonpowpow" => "Jurassic Park",
    "cardsoftheheart" => "Yu-Gi-Oh! The Sacred Cards, Pok&eacute;mon Puzzle Challenge",
    "crawek" => array("add" => array("screenname" => "CrAwEk", "synopsis" => "Secret of Evermore")),
    "eggmanimn" => array("add" => array("screenname" => "EggmaniMN", "synopsis" => "Zone of the Enders 2, MagnaCarta 2, Gumby vs The Astrobots")),
    "Azurinel" => array("add" => array("screenname" => "Azurinel", "synopsis" => "Eternal Daughter")),
    "mithical9" => "Kabuki: Quantum Fighter",
    "ahhee" => "DuckTales Remastered",
    "mashystrr" => "DuckTales, Rocket: Robot on Wheels",
    "zakkydraggy" => "Journey to Silius and mostly various NES/SNES stuff",
    
  ),
);

$include = array('user_name', 'channel_id', 'channel_name', 'channel_url', 'embed_stream', 'online', 'api');
$callback = 'sda_stream';
$ttl = 1;

$post = function(&$s) {
  $s->set_embed_dimensions(320, 260);
};

require_once 'latest_update.php';
SDAExceptions::set_error_level(E_USER_NOTICE);
$output = array('sda' => SDALatestUpdate::get()->results);
