<?php

/*
  Channel List
*/
$apis = array(
  'ustream' => array(
    "animustactics" => "Batman, Castlevania RoB &amp; SotN, Final Fantasy VII, requests",
    "asdfljg" => "Sonic 4 Episode 1", // Parax
    "battalion-wars-2-speedrun" => "Batallion Wars 2",
    "bio-shock-2" => "Bioshock 2",
    "bluestarreturnssda" => "Mario 64, Zelda: OoT, and Diddy Kong Racing",
    "cave-story-low-speedrun" => "Cave Story",
    "deign" => "Donkey Kong Country",
    "dotjd" => "Super Metroid, Rocket Knight Adventures",
    "dragonfang" => "Chibi Robo",
    "droogie-like-whoa" => "Super Mario 1 and 3, Super Mario World 2, Metal Gear Solid 2",
    "Electrochock" => "Random Stuff",
    "exes-stream" => "Super Mario 64, Biohazard 2, Zelda: Ocarina of Time, other gaming",
    "ffgamer86" => "Spanky's Quest, LTTP, Other",
    "i-like-glasses" => "Zelda: A Link to the Past", // Kryssstal
    "icheatatgolf" => "Super Metroid",
    "idkbutlike2" => "Playing whatever I want, whenever I want, and however I want!",
    "justingroton-gamez" => "Kirby's Epic Yarn, Donkey Kong Jungle Beat",
    "kareshi-tv" => "Super Ghouls 'n Ghosts high score, Ghosts 'n Goblins, Jaws",
    "kbladeruns" => "Stuff",
    "let-s-play-mass-effect" => "Mass Effect 2",
    "manjackal" => "Jackal",
    "mega-man-2-ta" => "Megaman series",
    "milessmb" => "Metroid Prime 1/2",
    "nhouzxm" => "Generic gaming",
    "opario" => "Ico, Shadow of the Colossus, Kingdom Hearts, KH: Chain of Memories, KHII",
    "riskbreakery" => "Double Dragon 3",
    "sprintgod" => "Braid, Streets of Rage 2",
    "strangenessdss" => "Blast Corps, Wario World, other stuff",
    "the-khan-zone" => "Air Fortress, Double Dragon",
    "toufool31" => "Super Mario Galaxy 2",
    "ucpro-s-speedrun-attemtps" => "Super Mario Bros. Wii",
    "vorpaledge" => "Rocket Knight Adventures, Super Metroid",
    "worxx" => "ALTTP, Mario Kart, Mario RPG, Off-Road, Donkey Kong Country, Castlevania, Super Metroid",
    "mrspeedrun" => "Metroid Prime 2 Echoes",
    "insert-title1" => array("add" => array("synopsis" => "PlayStation Platformers and/or challenge runs", "screenname" => "I have no name")),
  ),
  "justin" => array(
    "0xwas" => "Stuff",
    "aleckermit" => "007: Agent Under Fire",
    "alexandrebritos" => array("add" => array("synopsis" => "Mirror's Edge", "screenname" => "Brossentia")),
    "andrewg1990" => "Mario (duh), classic arcade games",
    "animeowzerz" => "Mystical Ninja 64, Donkey Kong 64, Zelda OoT",
    "aphox" => "The Witcher 2", // Lordy
    "arrowspace" => " ",
    "axelryman" => "Kingdom Hearts 2 and random stuff",
    "axon64" => "Mega Man X",
    "brsmstr" => array("add" => array("synopsis" => "Wii, Xbox 360", "screenname" => "Brassmaster")),
    "calebhart42" => "Megaman X",
    "call_me_greedo" => "Aria of Sorrow, Zero Mission, other Castleroids, Zelda",
    "carcinogensda" => "Resident Evil",
    "carlsagan42" => "Yoshi's Island",
    "cheaterhater" => "Tony Hawk's Pro Skater 4",
    "chumlum" => "Rocket Knight Adventures, Touhou",
    "cody_miller" => "Super Meat Boy",
    "cosmowright" => "Super Monkey Ball, Ocarina of Time",
    "cpkaka" => "Super Mario 64, Super Street Fighter 4",
    "crypticjacknife" => "DKC series (including DKCR), Turok: Evolution",
    "cyghfer" => "Currently: Super Mario RPG & Trip World",
    "darkeye14" => "Metroid Prime, Rocket Knight Adventures, Contra: Hard Corps, Super Metroid, SM64",
    "darkwing_duck_sda" => array("add" => array("synopsis" => "Older Nintendo games", "screenname" => "Darkwing Duck")),
    "dee_ehn" => "Zelda (Link to the Past primarily), Megaman, Castlevania, Mario, RPGs, racing",
    "dessyreqt" => "Super Metroid, Mega Man X, SotN, and SM64",
    "duckfist" => "Megaman 10",
    "dunnius" => "NES Metal Gear, ActRaiser 1, TASing",
    "eisenefaust" => "FF2 and random games",
    "elminster45" => "Ocarina of Time, The Wind Waker",
    "feasel" => "Snake Rattle N Roll, Rescue Rangers, Limbo, etc",
    "flickyish" => "Bayonetta",
    "fragmaster01" => "Iji",
    "hacksaw11" => "Lufia 2, SNES games",
    "heidrage" => "Summoner: A Goddess Reborn, Super C, other stuff",
    "honorablejay" => "Arkham Asylum, Jedi Academy, Vampire: Bloodlines",
    "hurblat" => "Contra 3",
    "ilseroth" => "Fable 2",
    "indextic" => "The Darkness",
    "ingx24" => "Majora's Mask, Ocarina of Time, Super Mario 64",
    "joe69420" => "Super Meat Boy, Super Mario 64",
    "khaos4wood" => "Resident Evil series, PC FPS games, other random stuff",
    "kibb0" => "Serious Sam",
    "kingnahum18" => "X-Men, Metroid Fusion",
    "kiyura" => "Enter the Matrix",
    "klaige" => "Rescue Rangers, Final Fight 3",
#    "ktwo123" => "NES",
    "lagdotcom" => "Klonoa 2",
    "lambdan" => array("add" => array("synopsis" => "Super Mario 64, Zelda OoT, and random", "screenname" => "DJS")),
    "link98" => "Zelda: Ocarina of Time",
    "lxx4xnx6xxl" => "Super Metroid",
    "manbearpig7" => "Link to the Past, Megaman 10, Super Mario 64, Super Mario Bros. 3", // Mr. Piggy
    "masterwill" => "Final Fantasy VI and Zelda: A Link to the Past",
    "mecha_richter" => "Castlevania SOTN Richter, poverty games",
    "megaultrajman" => "La-Mulana, lots of random gaming",
    "metasigma" => "Mega Man X, Red Star, RPGs",
    "mike89sda" => "Sonic 3, other funky stuff",
    "mikwuyma" => "Sunset Riders, random games",
    "mister___k" => "Contra 3",
    "moizt" => "Wario Land 2, Pok&eacute;mon Blue",
    "murderbydeath" => "A Link To The Past",
    "naegleria" => "Sonic 1, Shadow of the Colossus, random stuff",
    "obdajr" => "Megaman 7, Misadventures of Tron Bonne, Legend of Dragoon, Link to the Past",
    "oozaroo1" => "Symphony of the Night, random games",
    "peaches__" => "Blast Corps",
    "pheenoh" => "Ocarina of Time",
    "pjdicesare" => "Battletoads, Actraiser, Lagoon, 7th Saga, other misc bad games",
    "playe" => "Ocarina of Time, Metroid Prime 1/2, Majora's Mask",
    "pokeyil" => "Ocarina of Time",
    "puwexil" => "Kingdom Hearts series, Final Fantasy series, other Action RPGs/JRPGs",
    "quirkee" => "OoT, Trauma Center Second Opinion, others",
    "raelcun" => "Starcraft 2, random RPGs",
    "raijinnoxblade" => "Megaman X series, other stuff",
    "raneofsotn" => "SOTN, Seiken Densetsu 3, Brain Lord, Ninja Warriors",
    "reaif" => "Zelda, Super Metroid and others",
    "red_kryal" => "Mega Man Xtreme 2, other random stuff",
    "rggibson" => "Mega Man classics, random Genesis games",
    "ringrush" => "Donkey Kong 64, Sonic and the Secret Rings, Banjo Kazooie",
    "rolanmen1" => "Megaman X and Zero Series, Sometimes TASing",
    "romscout" => "Mario RPG, SOTN, Kirby's Dream Land",
    "runnerguy2489" => "3D Zelda series",
    "shaddod2" => "Legend of Zelda series, Final Fantasy Crystal Chronicles",
    "shadowjacky" => "Rocket Knight Adventures, Aero The Acrobat, Misc",
    "sicko2012" => "THE GREAT SICKO http://www.youtube.com/watch?v=UBbhTdCf6SM#t=57s",
    "siglemic" => "Super Mario 64",
    "slipomatic" => "Random gaming",
    "sonikkustar" => "Metal Slug",
    "speeddemosarchivesda" => "Believe it.",
    "sportacus84" => "Random gaming",
    "srkfunkdoc" => "Castlevania 1/3/4, FF Mystic Quest, Maximum Carnage, lots of obscure stuff",
    "stevethedreamer" => "He's Steve. He's a dreamer.",
    "sunjiano" => "Super Mario 64, Super Monkey Ball",
    "surreal_" => "Megaman X1/2, Twilight Princess",
    "teekayy" => "Seiken Densetsu",
    "theonly0" => "Super Mario Galaxy",
    "the_hattori_hanzo" => "He's too cool for school. That's why he's at university.",
    "tiki77747" => "Mega Man classic & X series",
    "tjp7154" => "Donkey Kong Country, Dark Cloud 2",
    "toothache42" => "Alisia Dragoon",
    "tranquilite" => "VVVVVV, casual stuff",
    "trihex" => "Super Mario World 2: Yoshi's Island",
    "tropicallo_" => "Donkey Kong (GB)",
    "unpronounceable" => "Dr. Mario, Cave Story", // mocliamtoh
    "uraniumanchor" => "Blaster Master, random stuff",
    "venick409" => "Megaman Zero",
    "welpenhund" => "A Link to the Past, Legend of Zelda, Mario Kart, Portal 2",
    "wingedzyre" => array("add" => array("synopsis" => "Decap Attack, Sonic 3D Blast, random games", "screenname" => "Zyre")),
    "yggdrizzle" => "Mega Man Classic & X, other NES/SNES games", // rockmanchan
    "yoshiiscool" => "Megaman series",
    "zaibirquild" => " ",
    "zenicreverie" => "RPGs, Speedruns, and Backloggery Shenanigans",
    "rocmox" => "Majora's Mask",
    "dram55" => "Super Mario World, Yoshi's Island, Super Nintendo",
    "jazzmastergold" => "Streaming for fun with a side of speedrunning MW2 and Kirby: NiDL",
  ),
  "twitch" => array(
    "adam_ak" => "Sonic Chaos, Monster Hunter 3",
    "aftermathrar" => "Castlevania series, Darksiders",
    "breakdown777" => "An eclectic selection",
    "caracarnvi" => "Final Fantasy X, maybe other random games",
    "crystalseafate" => "Mega Man 9",
    "demitrius7" => "Final Fantasy IX, King of Dragons",
    "droogie1xp" => "Super Mario 1 and 3, Super Mario World 2, Metal Gear Solid 2",
    "essentiafour" => "Chrono Trigger and other RPGs",
    "exosda" => array("add" => array("synopsis" => "Everything", "screenname" => "Exo")),
    "fisherrob86" => "Stuff", // Mickey_Mage
    "gogobmn" => "Metal Gear Solid 2, Trauma Center/Team, Uplink, casuals",
    "ikomasoji" => "Mega Man X series, Brave Fencer Musashi, Blood Omen, other random games",
    "kariohki" => "Silhouette Mirage and random non-speedrun games",
    "mapler90210" => "Aria of Sorrow, Portal, and the occastional whims",
    "nitrodon" => "Cave Story",
    "oasiz____" => array("add" => array("synopsis" => "GTA3 and random gaming", "screenname" => "oasiz")),
    "ozzy__88" => array("add" => array("synopsis" => "SotN and Super Castlevania IV", "screenname" => "ozzy88")),
    "paladrima" => "Ocarina of Time, Oracle of Seasons",
    "raen_" => "Wind Waker, The Legend of Zelda, and other great games",
    "skiazyk" => "Psychonauts",
    "youkaidragoon" => "Gears of War",
    "zallard1" => "Punch Out Wii, Splatterhouse, and Star Fox 64 highscores?",
    "dragondarchsda" => "Mostly RPGs, and some other randomages",
    "kinghippo423" => "Link To The Past, Legend of Zelda, Super Mario World, Super Mario 64, Where's Waldo",
    "trekhaakterror" => "Trekhaak's stream",
    "evussen" => "Steam games &amp; JRPGs",
    "greenalinksda" => "Direct Feed DS games, Nintendo/SEGA Consoles and XBLA",
    "uchihasda" => "F-Zero, Mario Kart, Metroid, Zelda series and other games",
    "zachsk" => "Flash gaming",
    "sir_vg" => "RPGs are the Spice of Life",
    "yoshifan28" => "Mario, Sonic, and others",
    "lee_sda" => "Yoshi's Island practice, and other failtastic endeavors",
    "svenne1138" => "Speedruns &amp; Races, the Sm&ouml;rg&aring;sbord of Life!",
    "cfox7" => "Super Mario 64, Ocarina of Time",
    "lee_sda" => "Yoshi's Island practice, and other failtastic endeavors",
    "c_moooh" => "Genesis games and Serious Sam",
    "tompa" => "Zelda and SNES",
    "z1mb0bw4y" => "Alice: Madness Returns, Super Meat Boy",
    "emptyeye" => "That Guy in the Cape",
    "kruzz" => "Stuff",
    "theenglishman" => "Resident Evil 4, Batman: Arkham City",
    "theseawolf1" => "Castlevania 2: Simon's Quest",
    "yingofsweden" => "Rockman X/X3, Mega Man 10, Klonoa",
    "edenalsda" => "World of Illusion, Tiny Toon Adventures: Buster Busts Loose!",
    "murphagator" => "Rollergames",
    "xelotath" => array("add" => array("synopsis" => "Rollergames and other games", "screenname" => "Xelotath")),
    "shiden86" => array("add" => array("synopsis" => "Ys &amp; Mega Man 6 plus other stuff", "screenname" => "Shiden")),
    "chrnothesinner" => "Skyrim speedrunning and other bowl clippory!",
    "andreluclevesque" => array("add" => array("synopsis" => "Amnesia, Super Meat Boy, Paper Mario, Tales of Symphonia, Mario Sunshine and Lost Kingdoms 2", "screenname" => "Andr&eacute;LucL&eacute;vesque")),
    "ChristosOwen" => "Speedruns &amp; Races",
    "lemonsx" => array("add" => array("synopsis" => "Terranigma and other RPGs", "screenname" => "Lemon")),
    "thesundaysequencebreak" => array("add" => array("synopsis" => "Live speedrunning chat", "screenname" => "The Sunday Sequence Break")),
  ),
);

$include = array('user_name', 'channel_name', 'channel_url', 'embed_stream', 'online', 'api');
$callback = 'sda_stream';
$ttl = 0.5;

$post = function(&$s) {
  $s->set_embed_dimensions(320, 260);
};

SDAExceptions::set_error_level(E_USER_NOTICE);
